### ISSUE TITLE
Add VTIMEZONE / tzinfo Serialization and better TZID Parsing

### ISSUE THREAD

**Issue by bhavik2491** [ics-py/ics-py#129]
Do we provide VTIMEZONE support while creating ics file ?
If yes then kindly refer which API needs to get called ?

**Comment by C4ptainCrunch** [comment]
We don't have this at the moment. I don't have time to implement it but feel free to submit a PR, i'll try to merge it :)

**Comment by N-Coder** [comment]
So it turns out that collecting the information needed for a `VTIMEZONE` declaration is actually pretty hard. Python does not provide an interface for extracting this information from generic `tzinfo` objects. Even the [dateutil `tzical` object](https://dateutil.readthedocs.io/en/stable/_modules/dateutil/tz/tz.html#tzical) we use for parsing a `VTIMEZONE` component into a python `tzinfo` object doesn't officially expose the details needed for serializing it again. Then there are also at lot of completely different `tzinfo` implementations ([1](https://docs.python.org/3/library/datetime.html#timezone-objects) [2](https://dateutil.readthedocs.io/en/stable/tz.html) [3](http://pytz.sourceforge.net/), and of course windows does [its own thing](https://dateutil.readthedocs.io/en/stable/tzwin.html)) and getting an even somewhat canonical name is [not quite possible](https://docs.python.org/3/library/datetime.html#datetime.tzinfo.tzname). Furthermore, there might be timezone names which are localized to some language or are only valid on the current system and are unknown on other systems (this is especially problematic when trying to load an ics file referring to a localized windows timezone on linux, i.e. ics files without explicit `VTIMEZONE` information are not portable). Even the Olson names might be problematic if the underlying definitions are outdated (which should be a very rare edge case).

Having a look at [ical4j](https://github.com/ical4j/ical4j/wiki/Timezones), they completely cut out any weird system timezone databases and only use their own `VTIMEZONE`-backed `TimeZone` implementation. To still be able to create ics files without their users having to define the timezone manually, they carry their [own version](https://github.com/ical4j/ical4j/wiki/Timezones#ZoneInfo) of the Olson database, converted to `VTIMEZONE` format using [tzurl](https://github.com/benfortuna/tzurl). Those guys even started working on a [python converter](https://github.com/benfortuna/tzurl/commit/31bfdfa1ad3ce79b132f9bf1c6137cb7d668f7e3) between the Olson database and `VTIMEZONE` declarations, but there have been no news since summer 2019. The JavaScript mozilla-comm/ical.js library [also uses](https://github.com/mozilla-comm/ical.js/issues/195) this project, and there also is a [wrapper library](https://github.com/mifi/ical-expander) for better handling of ics files with `RRULE`s and timezones (with which they also seem to have [some](https://github.com/mozilla-comm/ical.js/issues/294) [issues](https://github.com/mozilla-comm/ical.js/issues/102)). The `libical` seems to parse the [system `zones.tab`](https://github.com/libical/libical/blob/master/src/libical/icaltimezone.c#L1651). They also have a (quite outdated and [seemingly broken](https://github.com/libical/libical/issues/201)) [python wrapper](https://github.com/libical/libical/blob/master/src/python/Libical.py), which might be helpful nonetheless.

So it seems that most libraries are focussed on the IANA / Olson timezones that ship as `zones.tab` with most UNIX systems, while some also support the Windows timezone names (which can be converted to the IANA names as described [here](https://stackoverflow.com/questions/16156597/how-can-i-convert-windows-timezones-to-timezones-pytz-understands), see also [here](https://github.com/regebro/tzlocal/blob/master/tzlocal/win32.py)).

We currently support parsing and using `VTIMEZONE` objects through `dateutil`. Serializing `tzical` objects as generated by ical or possibly manually by a user should also be doable. We also support parsing and using any `TZID` that `dateutil` [understands](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.gettz), but getting a canonical name or even the `VTIMEZONE` representation of arbitrary `tzinfo` objects for serialization is very very hard. Thus, I'd currently resort to handling the easy cases as good as possible and ignoring all the problems with the hard cases, hoping that the target system somehow understands whatever information we were easily able to extract and is able to infer the missing pieces (as we currently do by resorting to `dateutil.tz.gettz`). To catch compatibility problems early we maybe could include a warning if we are serializing a `TZID` that doesn't seem to be well-known -- if we come up with a way to detect (maybe `from pytz import all_timezones, common_timezones`). Converting arbitrary timezones (or their names) to `VTIMEZONE` objects like `tzurl` or `libical` do is probably out of scope right now.

**Comment by N-Coder** [comment]
Possible python values we might want to serialize (only covering the built-in, `dateutil` and `pytz` types):
- VTIMEZONE:
	[`dateutil.tz.tzical`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzical)
- UTC:
	[`datetime.timezone.utc`](https://docs.python.org/3/library/datetime.html#datetime.timezone.utc),
	[`dateutil.tz.tzutc`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzutc),
	[`pytz.utc`](http://pytz.sourceforge.net/#localized-times-and-date-arithmetic)
- UTC-Offset:
	[`datetime.timezone`](https://docs.python.org/3/library/datetime.html#timezone-objects),
	[`dateutil.tz.tzoffset`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzoffset)
- Local Time:
	[`dateutil.tz.tzlocal`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzlocal),
	[`dateutil.tz.tzwinlocal`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzwinlocal),
	[`tzlocal pytz.timezone`](https://github.com/regebro/tzlocal),
	[`dateutil.tz.tzfile('/etc/localtime') == gettz()`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.gettz)
- Olson / IANA Database:
	[`dateutil.tz.tzfile (gettz)`](https://dateutil.readthedocs.io/en/stable/examples.html#tzfile-examples),
	[`pytz.timezone`](http://pytz.sourceforge.net/)
- Windows:
	[`dateutil.tz.tzwin`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzwin)
- POSIX / GNU TZ String:
	[`dateutil.tz.tzrange`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzrange),
	[`dateutil.tz.tzstr`](https://dateutil.readthedocs.io/en/stable/tz.html#dateutil.tz.tzstr)

Possible ics values / timezone names we want to parse:
- [Timstamp `-Z`](https://tools.ietf.org/html/rfc5545#section-3.3.5) or `TZID=UTC`
- Local Time ([Floating](https://tools.ietf.org/html/rfc5545#section-3.3.5)/[Naive](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects))
- [VTIMEZONE Component](https://tools.ietf.org/html/rfc5545#section-3.6.5)
- [IANA / Olson Timezone Identifier](https://en.wikipedia.org/wiki/Tz_database)
- [POSIX / GNU TZ](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html)
- UTC-Offset ([`UTC-1`, `UTC+1`](https://en.wikipedia.org/wiki/List_of_UTC_time_offsets), [`GMT-1`, `GMT+1`](https://en.wikipedia.org/wiki/Greenwich_Mean_Time),...)
- [Windows TZ Key](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.getsystemtimezones?view=netframework-4.8), possibly [localized](https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.displayname?view=netframework-4.8#System_TimeZoneInfo_DisplayName) (see also [here](https://stackoverflow.com/questions/16156597/how-can-i-convert-windows-timezones-to-timezones-pytz-understands) and [`tzlocal`](https://github.com/regebro/tzlocal/blob/master/tzlocal/win32.py#L25))
	On Windows, these can be interpretend and translated using the registry (see `tzlocal`). Otherwise, CLDR ([1](https://www.unicode.org/cldr/charts/latest/verify/zones/index.html), [2](http://cldr.unicode.org/translation/timezones)) has data on how to translate timezone names and how to convert them to Olson names (see [`pytz l18n`](https://github.com/tkhyn/l18n) and `tzlocal`).
