### ISSUE TITLE
Timestamp seconds are ignored

### ISSUE THREAD

**Issue by C4ptainCrunch** [ics-py/ics-py#182]
See https://github.com/C4ptainCrunch/ics.py/pull/113

> A timestamp which contains seconds, e.g. 2018-02-19 12:00:05 will be stored as 2018-02-19 12:00:00. In my opinion seconds are irrelevant here, but it was surprising none-the-less.

**Comment by N-Coder** [comment]
We should now have a test case that checks this and prevents regressions:
https://github.com/C4ptainCrunch/ics.py/blob/01172505f3eebc792a6a3445a00f2ef0aed9b80d/tests/issues/gh182.py
While this issue was probably solved long ago, this test also passed with the latest version of the `timezones` branch, so this issue should be solved (it will be closed once we merge the branch):
https://github.com/C4ptainCrunch/ics.py/runs/792496212

Further note: The ics format doesn't support milli- or microseconds, while the resolution for pythons `datetime` objects is 1 microsecond. Thus, if you serialize a `datetime` object with a sub-second part (e.g. `datetime.now()`), this part will be lost and the deserialized object will consequently differ by the lost microseconds.

**Comment by aureooms** [comment]
> Further note: The ics format doesn't support milli- or microseconds, while the resolution for pythons datetime objects is 1 microsecond. Thus, if you serialize a datetime object with a sub-second part (e.g. datetime.now()), this part will be lost and the deserialized object will consequently differ by the lost microseconds.

It is rounded down? Is it clear that this should be rounded down? I think it should. Docs should be explicit about that.

**Comment by N-Coder** [comment]
The RFC doesn't say anything about how sub-second values should be handled, but we are simply ignoring them, which is equivalent to cutting them off / always rounding down. This isn't documented yet, but that should definitely be said (or maybe even shown) at some point.

The only thing we could still think about is forcing the Python representation to be in sync with the ics representation and therefore trying to keep out any further information which can't be represented by the file format, e.g. by already cutting of the sub-second part when setting the begin / end timestamp. This would preempt any confusion arising from serializing anything containing `datetime.now()` (i.e. any Event, as that is the default for `DTSTAMP`) and getting back something that compares unequal from deserializing the result again. On the other hand, this might lead to some people wondering where the microseconds went that they just passed to the Event's begin time setter, but I guess that would be the lesser evil and also easier to document / explain / debug / find / understand.
