### ISSUE TITLE
ArrowParseWarning: The .get() parsing method without a format string will parse more strictly in version 0.15.0

### ISSUE THREAD

**Issue by mobeigi** [ics-py/ics-py#284]
Howdy,

I use ICS for a package of mine and during unit tests I am seeing the following warnings:

```
C:\Users\Mo\.virtualenvs\fb2cal-IW7zb1ZR\lib\site-packages\arrow\factory.py:202: ArrowParseWarning: The .get() parsing method without a format string will parse more strictly in version 0.15.0.See https://github.com/crsmithdev/arrow/issues/612 for more details.
  warnings.warn(
C:\Users\Mo\.virtualenvs\fb2cal-IW7zb1ZR\lib\site-packages\arrow\factory.py:249: ArrowParseWarning: The .get() parsing method with a format string will parse more strictly in version 0.15.0.See https://github.com/crsmithdev/arrow/issues/612 for more details.
  warnings.warn(
.....
```

For more context see: https://github.com/crsmithdev/arrow/issues/612

Might want to fix the usage here.

**Comment by N-Coder** [comment]
Thanks for the heads up! We will remove the `arrow` dependency with the next version of `ics.py`, as it is unable to handle floating/local timestamps as defined by the ics standard. The commits for this are already in with PR #222, and iirc there were further breakages with `arrow` 0.15, which is why we pinned the version of the dependency. I doubt that there will be an intermediate release of `ics.py` that fixes the version compatibility, thus it's probably best to simply silence the warning.
