### ISSUE TITLE
parse error with LOCATION containing colon ':'

### ISSUE THREAD

**Issue by diemoschwarz** [ics-py/ics-py#290]
Hi, first of all, thanks for all the hard work that has gone into this library already!
I have a treasure trove of ~3k ics files authored in iCal that I need to upload to CalDAV, of which a few dozen raise exceptions in parsing.  Is it helpful if I try to identify the error and post an issue for each?
First example, [this ics](https://pastebin.com/FhUgAF8t) has a colon ':' in the (folded) location field:
```
LOCATION:xxxxxxxx xxxx\n119 r St xxxx\n750xx PARIS   01 43 57 xx xx fax 
 : 01 43 57 xx xx
```
which raises
```
  File "/Users/schwarz/.local/lib/python3.6/site-packages/tatsu/grammars.py", line 296, in parse
    return ctx._token(self.token)
  File "/Users/schwarz/.local/lib/python3.6/site-packages/tatsu/contexts.py", line 632, in _token
    self._error(token, exclass=FailedToken)
  File "/Users/schwarz/.local/lib/python3.6/site-packages/tatsu/contexts.py", line 453, in _error
    raise self._make_exception(item, exclass=exclass)
tatsu.exceptions.FailedToken: (1:3) expecting ':' :
01 43 57 xx xx
  ^
contentline
start

```
Please tell me if errors like this are relevant to the improvement of the library. Thanks!
Python 3.6.2
ics==0.7

**Comment by N-Coder** [comment]
Thanks for reporting this! Parser errors are very relevant, actually we're currently collecting a bigger base of example ics files for testing - see #236. If you can donate any of your files without privacy concerns (e.g. because they are available publicly on the web) that would be really cool.

Having an unescaped colon in the value is actually [allowed](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.11) for Text values, but iirc they are somewhat special due to this, so maybe this was overlooked in the old Tatsu parser. For the upcoming (whenever that might be) version 0.8, I completely rewrote the parser to a tremendously faster and more flexible one. Could you try using the current master branch or even the `timezones` branch from #249 (I'm currently waiting for @C4ptainCrunch to grant me the rights to properly merge that branch) for parsing your files? I was very focussed on standard compliance when writing the new parser, but it should also give us the flexibility to easily be more lenient where apropriate.

**Comment by diemoschwarz** [comment]
Thanks for the heads up! I think I could easily contribute redacted files. What's the best way to contribute?  Add them to some dir in the repository and send a pull request? Attach them to issues (zipped or renamed, since github doesn't allow .ics)? 
I'll try the new parser shortly.

**Comment by N-Coder** [comment]
> I think I could easily contribute redacted files. What's the best way to contribute? Add them to some dir in the repository and send a pull request? Attach them to issues (zipped or renamed, since github doesn't allow .ics)?

Awesome! As that corpus is still only in the PR and not in the main repository I guess the easiest thing would be to attach a zip with all of them to some comment there, so I won't forget them once I have time to continue working on that.

**Comment by N-Coder** [comment]
Just a small FYI: this works with the current `master` branch, but still having an example in the corpus that covers this (or actually any further examples) would be awesome!
```
>>> from ics.contentline import *
>>> string_to_container("""LOCATION:xxxxxxxx xxxx\n119 r St xxxx\n750xx PARIS   01 43 57 xx xx fax 
 : 01 43 57 xx xx
""")
ContentLine(name='LOCATION', params={}, value='xxxxxxxx xxxx\\n119 r St xxxx\\n750xx PARIS \u2028\u202801 43 57 xx xx\u2028fax : 01 43 57 xx xx', line_nr=0)
```
